### ISSUE TITLE
How to build & how to use?

### ISSUE THREAD

**Issue by Hankyu-Kim** [x-tools-author/x-tools#20]
1. how to build from source code to make .exe file or .sh file?

2. is there simple tutorial video for using this?

**Comment by x-tools-author** [comment]
https://github.com/x-tools-author/x-tools is my project but not  https://github.com/x-tools/xtools

**Comment by Hankyu-Kim** [comment]
I modified, can you answer those two questions?
Thank you.

**Comment by Hankyu-Kim** [comment]
While i build through qtcreator (qt6), i found this bug, do you know any solution for this?
It's saying like this :
C:\Users\user\Downloads\x-tools-6.0.3\x-tools-6.0.3\ThirdParty\glog-0.7.0\src\demangle.cc:50: error: dbghelp.h: No such file or directory
C:\Users\user\Downloads\x-tools-6.0.3\x-tools-6.0.3\ThirdParty\glog-0.7.0\src\demangle.cc:50:23: fatal error: dbghelp.h: No such file or directory
 #  include <dbghelp.h>
                       ^

![스크린샷 2024-09-20 131316](https://github.com/user-attachments/assets/9051415e-16b7-47df-9418-8f4920c00699)

**Comment by Hankyu-Kim** [comment]
I could build it by using qt 5.9.7
issue closed.

**Comment by Hankyu-Kim** [comment]
Can i ask why same message coming back from random port like 53799 when I only try to send udp packet to client (port 9092)?

Environment:
udp client (127.0.0.1 9092)
udp server (127.0.01 9090)

![스크린샷 2024-09-20 140411](https://github.com/user-attachments/assets/f441c455-816d-44bc-ac7c-e6c5f52f59a6)
