### ISSUE TITLE
问题:
UDP高级设置:广播设置下点击允许广播以及组播设置下点击允许组播，软件直接奔溃退出，功能无法使用
测试环境:3.5.0版本，Windows系统

### ISSUE THREAD

**Issue by Guokr1991** [x-tools-author/x-tools#22]

**Comment by Guokr1991** [comment]
Questions:
UDP Advance Settings: When Enable broadcast or Enable multicast, the software must be crashed, the function is not working.
Test Environment: Version 3.5.0，Windows

**Comment by x-tools-author** [comment]
不再维护旧版本
